### ISSUE TITLE
utcp-mirage confusion when using stack multiple times

### ISSUE THREAD

**Issue by hannesm** [robur-coop/utcp#22]
i.e. for both service and management... looks like there's some global state somewhere that needs to be removed

**Comment by palainp** [comment]
Hi, my knowledge with Ocaml isn't deeper enough, so I wonder if the timer counter in `src/tcptimer.ml:168` could be shared between the two stacks and leads to strange behaviors? (That the only relevant ref variable I found)

**Comment by hannesm** [comment]
I removed that ref variable.

The issue was rather my sloppyness in defining the stack, and still passing the `default_network` binding to some of the functions (instead of the `netif ~group:"foo" "foo").
